### ISSUE TITLE
ssh_config_file fails with "too many open files"

### ISSUE THREAD

**Issue by forrejam** [carlmontanari/scrapli#125]
When opening 100+ connections, and passing in ssh_config_file as part of the driver config, I get the following:
```
File "/home/jf/.local/lib/python3.8/site-packages/scrapli/driver/core/cisco_iosxe/async_driver.py", line 132, in __init__
File "/home/jf/.local/lib/python3.8/site-packages/scrapli/driver/network/async_driver.py", line 48, in __init__
File "/home/jf/.local/lib/python3.8/site-packages/scrapli/driver/generic/async_driver.py", line 40, in __init__
File "/home/jf/.local/lib/python3.8/site-packages/scrapli/driver/base/async_driver.py", line 13, in __init__
File "/home/jf/.local/lib/python3.8/site-packages/scrapli/driver/base/base_driver.py", line 178, in __init__
File "/home/jf/.local/lib/python3.8/site-packages/scrapli/driver/base/base_driver.py", line 381, in _update_ssh_args_from_ssh_config
File "/home/jf/.local/lib/python3.8/site-packages/scrapli/ssh_config.py", line 75, in __init__
OSError: [Errno 24] Too many open files: 'ssh_config.conf'
```

open 100+ connections using the following Driver dict

```
conn_info = {
      "host": ip, 
      "auth_username": ssh_username, 
      "auth_password": ssh_password,
      "auth_strict_key": False,
      "transport": "asyncssh",
      "driver": AsyncIOSXEDriver,
      "ssh_config_file" : "ssh_config.conf",
      }
  }

```

 - OS: Ubuntu 20

Am I misusing the scrapli config? It could be good to to pass the config in as a string instead of a file path and leave the file handle management to the user.

**Comment by carlmontanari** [comment]
Hey @forrejam !

There is defo optimization to be had here (more on that in a sec), that said.... 100 connections should for sure not be an issue for open files I would think/hope. Whats your ulimit set at? (good quick post on it [here](http://woshub.com/too-many-open-files-error-linux/)) I think probably cranking that up if its low is the fastest/easiest fix here. I think it probably gets opened once in scrapli and another time in asyncssh too, so 100 * at least 2 already gets close to a 256 ulimit without even counting connections and such.

> Am I misusing the scrapli config? It could be good to to pass the config in as a string instead of a file path and leave the file handle management to the user.

Not missing anything I dont think! I dont think(?? subject to changing my mind at any time!) I would change things to pass in an already loaded file as we also pass in the path to asyncssh for example. That said I think it would probably be a very good change to make sure that we only read the file once (at least in the Scrapli bits we control) -- I'd have to think about how to best implement that but I think it can be done fairly easily. 

Will tinker with it over the next week or so when I have some time. In the meantime hopefully the ulimit thing gets you goin! Let us know!

Carl

**Comment by carlmontanari** [comment]
Hey @forrejam -- I merged the (hopefully) fix into develop just now, so I'm going to close this. If you have some time to test it and if anything is wrong, please feel free to reopen this!

Carl

**Comment by forrejam** [comment]
Hi @carlmontanari , I am sorry I was not able to test this as my project got delayed, I should be able to test this again in the coming weeks I will let you know.

**Comment by carlmontanari** [comment]
Hey no worries @forrejam ! Just give a shout if its not working nicely now -- I think we should be good to go!

**Comment by forrejam** [comment]
Ok the ssh_config fix had definitely improved the issue but it turns out this was a symptom not the problem!

Upon looking into this further, using the linux command "lsof" I noticed my script was leaking TCP connections using the async driver. So this would explain why I hit the file descriptor limit of 1024. I moved my code to using the async context manager and in combination with the ssh_config fix, I am now able to hit thousands of devices without issue. 
```
async with driver(**scrapli_config) as conn: 
     prompt_result = await conn.get_prompt()
````
Thankyou for your help!

**Comment by carlmontanari** [comment]
Ohhhhhh.... I don't think it was you! It was me 😭 Looked at git blame cuz that sounded wrong/bad and found [this](https://github.com/carlmontanari/scrapli/pull/106/files#diff-9485dfa1a07d8df0eaba23e0f41b054530400305638a523afb0b3d6fe9a18ac4R122) -- so if you were on 2021.01.30 and recently upgraded to 2021.07.30 you should be good w/ either context manager or just `await close`.

In any case, really appreciate the updates and glad it is working out well for you -- thousands of devices sounds pretty awesome 😁 !!

Carl
