### ISSUE TITLE
Add a ignore_privilege_level flag to the send_command(s|fromfile) methods of the network driver 

### ISSUE THREAD

**Issue by tybruno** [carlmontanari/scrapli#137]
Adding an ignore_privilege_level boolean flag to `driver.network.sync_driver.send_command`, `driver.network.sync_driver.send_commands`, `driver.network.sync_driver.send_commands_from_file`, `driver.network.async_driver.send_command`, `driver.network.async_driver.send_commands`, and `driver.network.async_driver.send_commands_from_file`. This will allow the user to use whatever the current privilege level is on the device. 

For more information view this [discussion](https://github.com/carlmontanari/scrapli/discussions/128). 

Use Case:
As a developer, I want to be able to handle the privilege levels through the commands that I send instead of the standard Scrapli privilege management, so that at run time I can send arbitrary commands in different privilege levels.

**Comment by tybruno** [comment]
Hello @carlmontanari,

When trying to modify the send_commands_from_file to use the "ignore-privilege_level' I came across an issue. 

Trying to solve the issue as I did with send_command and send_commands I come across an issue when calling `super().send_commands_from_file`.  Because the superclass from generic calls send_commands(), the `super().send_commands_from_file` would also have to pass the `ignore_privilege_level` into the send_commands method it calls.

There are 3 main ways I think we could solve this but none of them are ideal in my opinion.
1.  `super().send_commands_from_file()` would need to take **kwargs that would internally pass **kwargs into the `send_send_commands` method that it calls.
2. Monkeypatch `super().send_commands_from_file()` to take the `send_commands(ignore_privilege_level=ignore_privilege_level)` 
3. Don't bother with having `send_commands_from_file(ignore_privilege_level)` since there is not a clean way of modifying to match the use case.
`
def send_commands_from_file(..., ignore_privilege_level=False):
        if not ignore_privilege_level:
            if self._current_priv_level.name != self.default_desired_privilege_level:
                self.acquire_priv(desired_priv=self.default_desired_privilege_level)

        if failed_when_contains is None:
            failed_when_contains = self.failed_when_contains

        return super().send_commands_from_file(
            file=file,
            strip_prompt=strip_prompt,
            failed_when_contains=failed_when_contains,
            stop_on_failed=stop_on_failed,
            eager=eager,
            timeout_ops=timeout_ops,
        )
`

**Comment by carlmontanari** [comment]
Hey @tybruno!

The issue you are describing with from file makes sense. I think perhaps the simplest answer is to just have some duplication.... obviously not super ideal, however scrapli already ends up having a fair bit of duplication because of the sync and async stuff so I'm a little less worried about it.

What if the network driver layer `send_commands_from_file` had something like:

```
        commands = self._pre_send_from_file(file=file, caller="send_commands_from_file")

        return self.send_commands(
            commands=commands,
            strip_prompt=strip_prompt,
            failed_when_contains=failed_when_contains,
            stop_on_failed=stop_on_failed,
            eager=eager,
            timeout_ops=timeout_ops,
            ignore_privilege_level=ignore_privilege_level,
        )
```

I think this may also help since it is kinda silly that the `send_commands_from_file` in network driver checks the privilege level, then ends up back at network driver `send_commands` which checks the privilege level again... so that seems like I did a bad design before and we can maybe clean it up a bit now :) 

Thoughts? 

If you could open a pr with your fork that would be super helpful for dropping comments and stuff and working through whatever!

Thanks for the work on this!

Carl

**Comment by tybruno** [comment]
Hey @carlmontanari!

Awesome suggestion! That is a much better design :). hahaha I always find it funny when looking at old code I write as well. I always find better ways I could have designed or implemented my code.

I'll go ahead and submit a PR

Thanks Carl!! 

Btw, at work I had someone send an email to 3 larger mailers discussing other Python libraries that handle device connections. I got a chance to advertise Scrapli and all its glory compared to other similar libraries ;). I am really excited about the future of Scrapli.

**Comment by carlmontanari** [comment]
will close this so we can get thing sorted out in #138
