### ISSUE TITLE
Feature request: username_prompt as regex for asynctelnet & telnet

### ISSUE THREAD

**Issue by davaeron** [carlmontanari/scrapli#146]
Remake "username_prompt" to use them as a regular expression so we can use multiple username prompts per session, like "sername|ogin" that i think will cover most of the switches.
https://github.com/carlmontanari/scrapli/blob/81d7700746fa41773b93601b9c909de5e3d9c2f2/scrapli/channel/async_channel.py#L347
What do you think?

**Comment by carlmontanari** [comment]
Yeah super good call... been on the todo list for a while but never got around to it. I can probably knock it out this weekend but if you are down to get a PR for it I'm happy to take a look!

**Comment by davaeron** [comment]
Here you are :smile:

**Comment by carlmontanari** [comment]
Hahah awesome! Will close this and we can follow up on the rest in the PR! Thanks a bunch!

Carl
