### ISSUE TITLE
Telnet "_handle_control_chars_response" gets stuck in the infinite loop

### ISSUE THREAD

**Issue by davaeron** [carlmontanari/scrapli#147]
Some of my switches sends in telnet:
IAC WILL ECHO
IAC WILL SUPPRESS-GO-AHEAD
before login prompt.
If they do not receive:
IAC DO ECHO
IAC DO SUPPRESS-GO-AHEAD
they will repeat control characters infinitely, so "_handle_control_chars_response" gets stuck in the infinite loop.
https://github.com/carlmontanari/scrapli/blob/81d7700746fa41773b93601b9c909de5e3d9c2f2/scrapli/transport/plugins/asynctelnet/transport.py#L86-L91

I've changed that code to:
```
            if cmd in (DO, DONT):
                # if server says do/dont we always say wont for that option
                self.stdin.write(IAC + WONT + c)
            elif cmd in WILL:
                # if server says will we always say do for that option
                self.stdin.write(IAC + DO + c)
            elif cmd in WONT:
                # if server says wont we always say dont for that option
                self.stdin.write(IAC + DONT + c)
```
And it works. No more loops.

**Comment by carlmontanari** [comment]
That makes sense -- I will test this out against all the lab devices and get it added once everything looks good. Probably will be later this week/weekend.

Thanks for opening this!

Carl

**Comment by carlmontanari** [comment]
I tested your fix against iosxe/iosxr/nxos/junos/eos and it worked great! I just pushed this to develop you can install develop directly like: `pip install -e git+https://github.com/carlmontanari/scrapli.git@develop#egg=scrapli` to test it out. Thanks a bunch for opening this and providing the fix! I'll close this now, but feel free to reopen if I got something wrong in the fix!

Carl

**Comment by davaeron** [comment]
Thank you!

**Comment by davaeron** [comment]
Found some issues with DO/DONT.
This works for me:
```
if cmd in DO:
    # if server says do we say will for that option
    self.stdin.write(IAC + WILL + c)
elif cmd in DONT:
    # if server says dont we say wont for that option
    self.stdin.write(IAC + WONT + c)
elif cmd in WILL:
    # if server says will we always say do for that option
    # see also: #147 thank you to @davaeron!
    self.stdin.write(IAC + DO + c)
elif cmd in WONT:
    # if server says wont we always say dont for that option
    self.stdin.write(IAC + DONT + c)
```

**Comment by davaeron** [comment]
@carlmontanari

**Comment by carlmontanari** [comment]
Hah, tricky telnet!!! I'll give this a shot sometime this week or weekend at the latest. If you're up for a it a PR against dev would be great, otherwise I can get it added after I test it out.

Thanks for the help yet again!

Carl

**Comment by carlmontanari** [comment]
Hey @davaeron 

Can you give this a try: 

```
            if cmd == DO and c == TERM_TYPE:
                self.stdin.write(IAC + WONT + c)
            elif cmd in (DO, DONT):
                # if server says do/dont we always say wont for that option
                self.stdin.write(IAC + WONT + c)
            elif cmd == WILL:
                # if server says will we always say do for that option
                # see also: #147 thank you to @davaeron!
                self.stdin.write(IAC + DO + c)
            elif cmd == WONT:
                # if server says wont we always say dont for that option
                self.stdin.write(IAC + DONT + c)
```

Responding to `term type` control code with `WILL` seemed to break stuff for eos and nxos (iosxe was still good -- not sure what platform you are using). I didn't look *too* closely yet but it looks like iosxe just didn't send the terminal type whereas that was the first control code from eos/nxos.

With the above it looks like iosxe, iosxr, nxos, eos, and junos all work in my little test setup.

**Comment by davaeron** [comment]
`if cmd == DO and c == TERM_TYPE:
                self.stdin.write(IAC + WONT + c)
            elif cmd in (DO, DONT):
                # if server says do/dont we always say wont for that option
                self.stdin.write(IAC + WONT + c)`

Don't see a logic in here =)
It's the same "won't" twice.
I'll check what "cmd" my D-Links wants as a "WILL" and send it to you a little later this day.

**Comment by davaeron** [comment]
```
SGA = bytes([3]) # suppress go ahead

if (cmd == DO) and (c == SGA):
    # if server says do suppress go ahead we say will for that option
    self.stdin.write(IAC + WILL + c)
elif cmd in (DO, DONT):
    # if server says do/dont we always say wont for that option
    self.stdin.write(IAC + WONT + c)
elif cmd in WILL:
    # if server says will we always say do for that option
    self.stdin.write(IAC + DO + c)
elif cmd in WONT:
    # if server says wont we always say dont for that option
    self.stdin.write(IAC + DONT + c)
```
@carlmontanari please test this.
Oh so tricky telnet!

**Comment by carlmontanari** [comment]
> Don't see a logic in here =)
It's the same "won't" twice.

Hahah yea, my bad :D I think I was intending to say if we see term type say WILL then for everything else say WONT (like how your proposed setup is), but clearly was out of thinking power for the day 😁 

I'll give this updated setup a try later today and report back!

Carl

**Comment by carlmontanari** [comment]
Ok, tested your fix and looks like everything is working as expected on all the test platforms I have!

Let me know if you wanna PR or want me to just slap it in there, up to you!

Thanks for the help with this!

Carl

**Comment by davaeron** [comment]
Just slap it in, Carl!
Thank you!

**Comment by carlmontanari** [comment]
Awesome, just pushed to develop. Thanks again! Hopefully this is the last of the asynctelnet gremlins! 😁
