### ISSUE TITLE
Async Drive exception

### ISSUE THREAD

**Issue by zhangineer** [carlmontanari/scrapli#152]
I am getting the following exceptions when using Async.

scrapli.exceptions.ScrapliValueError: provided transport is *not* an asyncio transport, must use an async transport with the AsyncDriver(s)

**Here is my code, it runs fine without Async driver.**

from scrapli.driver.core import AsyncIOSXEDriver
import asyncio

MY_DEVICE = {
    "host": "10.100.0.12",
    "auth_username": "username",
    "auth_password": "password",
    "auth_strict_key": False,
}

async def main():
    """Simple example of connecting to an IOSXEDevice with the AsyncIOSXEDriver"""
    async with AsyncIOSXEDriver(**MY_DEVICE) as conn:
        # Platform drivers will auto-magically handle disabling paging for you
        result = await conn.send_command("show run")

    print(result.result)

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())

also, is it possible to add a feature to be able to parse in offline mode ? (i.e. parse based on text files)

Thanks
Peter

**Comment by zhangineer** [comment]
my own fault. I did not add "transport" to the device dictionary.

**Comment by carlmontanari** [comment]
@zhangineer -- Glad you got it sorted!

Regarding your question:

> also, is it possible to add a feature to be able to parse in offline mode ? (i.e. parse based on text files)

Yeah, you could use one of the "helper" functions [here](https://github.com/carlmontanari/scrapli/blob/master/scrapli/helper.py#L80-L202). Hope that helps!

Carl
