### ISSUE TITLE
Hashed host names/addresses in known_hosts are not supported

### ISSUE THREAD

**Issue by kangtastic** [carlmontanari/scrapli#174]
I recently ran into an issue using SSH key-based authentication and strict host key checking. I was getting tracebacks with `scrapli.exceptions.ScrapliAuthenticationFailed: 172.18.0.11 not in known_hosts!` despite knowing for sure that I had connected to that host before.

This was apparently due to having `HashKnownHosts yes` set in my `ssh_config` file, which applies hashing to the host identifier field of new entries in a `known_hosts` file:

```
# An unhashed entry
172.18.0.11 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC...

# The same entry, but the host address is hashed
|1|7bElFvrtgI2+a1RXLTrM6WsAnfw=|bbO+1Ns+K5Uw+swY0xs0aQkzJfI= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC...
```

While parsing a `known_hosts` file and creating a `SSHKnownHosts().hosts` dict, scrapli doesn't do anything special with the hashed host, and the key for the dict entry ends up being `"|1|7bElFvrtgI2+a1RXLTrM6WsAnfw=|bbO+1Ns+K5Uw+swY0xs0aQkzJfI="`.

Here's where it was falling over for me, in `transport/ssh2/transport.py:Ssh2Transport._verify_key()`, lines 96-101:
```py
        known_hosts = SSHKnownHosts(self.plugin_transport_args.ssh_known_hosts_file)

        if self._base_transport_args.host not in known_hosts.hosts.keys():
            raise ScrapliAuthenticationFailed(
                f"{self._base_transport_args.host} not in known_hosts!"
            )
```

Fortunately, computing the hash can be easily done with Python builtins. The hash algorithm is standard HMAC-SHA1 and its format in the `known_hosts` file is as follows:
- `|1|`: A magic number. `HASH_MAGIC` in the OpenSSH sources.
- A Base64-encoded representation of a random salt (i.e. the secret key mentioned in RFC 2104).
- `|`: A pipe character as a separator.
- A Base64-encoded representation of the result after hashing the host identifier using the salt (i.e. after running HMAC-SHA1 using the salt as the key and the host name/address as the message).

I have a PR more or less ready to go, but before that, your thoughts? Comments? Questions?

**Comment by carlmontanari** [comment]
Hey @kangtastic thanks for opening this, and for the great explanation!

Absolutely open to a PR for this, sounds like it would be a great addition, and love that it can be done all with standard library. Looking forward to checking it out!

Carl

**Comment by carlmontanari** [comment]
Awesome PR merged, closing this 🚀 !
