### ISSUE TITLE
code stops when there is a '-' (minus) in the 'input'

### ISSUE THREAD

**Issue by TmyWu** [carlmontanari/scrapli#205]
Hello,

I have been struggling with something. I'm just trying to send network commands with Cisco IOSXE. 
Whenever there is a '-' in the send_configs(), It just stops and give error: connection not opened, but attempting to call a method that requires an open connection, do you need to call 'open()'?

while checking the logs everything seems ok. Except for the place where there is a '-' : 
interface video-ani agc-mode optical offset -8\x08\x08\x08\x08\x08\x08\x08\x08
I'm sending the command "interface video-ani agc-mode optical offset -8"
I've also changed the 'internal' files, specifically the base_driver pattern to  pattern=r"^.+#$" (and other forms where it's "accept everything") without any difference. It just keeps bugging out at the '-'. If I remove the - it works fine, but that is not what I need configured

**Comment by carlmontanari** [comment]
Can you provide the log output and your script please? 

The `\x08` is the terminal repainting the prompt. If this is on IOSXE device we *should* have ran `terminal width 511` which means unless you have a crazy long input we shouldn't be seeing this repainting.

**Comment by TmyWu** [comment]
Thank you for your help. I just shorten the command instead of writing it out. 
I'm on a older network device that is not IOSXE and does not have terminal width command. But thank you anyways
