### ISSUE TITLE
requirements.txt missing in pypi release

### ISSUE THREAD

**Issue by blkmajik** [carlmontanari/scrapli#216]
**Describe the bug**
setup.py requires the use of requirements.txt, but it is missing from the pypi sdist file.

**To Reproduce**
build from sdist source

python3 setup.py build

**Expected behavior**
project would bulid properly

**Stack Trace**
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    with open("requirements.txt", "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

**OS (please complete the following information):**
 - OS: CentOS 7

**Additional context**

**Comment by carlmontanari** [comment]
Good catch. Happen to know the "best" way to include nowadays? Is it still MANIFEST.in or is there something nicer/better that works w/ standard setup.py stuff?

Thanks!

Carl

**Comment by blkmajik** [comment]
Yeah as far as I know it's still MANIFEST.in if you are using setup.py

**Comment by carlmontanari** [comment]
Cool, thanks! I'll poke around with that this weekend hopefully. Unless its critical for ya for some reason I probably won't bother with cutting a new release again till the "regularly scheduled" cycle (1/30 and 7/30).

**Comment by carlmontanari** [comment]
Thanks again for raising this, will merge #217 to develop here in a sec -- it includes manifest.in grabbing all the requirements files! Like I said, won't make another release until 7/30, unless you have some burning need (in which case I can just push out a post release to 1/30 version).
