### ISSUE TITLE
No matching key exchange found for host

### ISSUE THREAD

**Issue by ialshaev** [carlmontanari/scrapli#227]
Hey,

when I execute the script that uses scrapli to connect to my lab I am always getting the following error:
scrapli.exceptions.ScrapliAuthenticationFailed: No matching key exchange found for host, their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
-it may be possible that you pruned legacy/unsecure KEX methods - I can understand that

I tried to explicitly set the transport option to 'system' - did not help. Also tried to dig into the code and it seems like this msg is getting from system itself and then popped in the output by Exception Handler. If that is true - I confused why scrapli sees the message "No matching key exchange found for host, their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1" as when I ssh'ing to the device I do not receive it (my ssh_config has these legacy diffie-hellman algos included, I added the, manually).

**Comment by carlmontanari** [comment]
> as when I ssh'ing to the device I do not receive it (my ssh_config has these legacy diffie-hellman algos included, I added the, manually).

you need to tell scrapli to use your ssh config file
