### ISSUE TITLE
Use system's ssh_config file by default

### ISSUE THREAD

**Issue by josephwhite13** [carlmontanari/scrapli#228]
I have a quick question/recommendation. Can the system's ssh configuration be used by default?

I see `-F /dev/null` is being added to the ssh command if a config file wasn't provided. Can this be removed?
https://github.com/carlmontanari/scrapli/blob/master/scrapli/transport/plugins/system/transport.py#L109-L110

Great work on this project!

**Comment by carlmontanari** [comment]
yep, just pass `ssh_config_file=True` this looks in /etc/ssh/ssh_config and ~/.ssh/config, or you can pass a string if you have a config file at another location.

**Comment by carlmontanari** [comment]
ah I re-read that now. "no", this default will not change, but you can pass `True` as mentioned.
