### ISSUE TITLE
send_interactive - doesn't seem to work for 'write erase'

### ISSUE THREAD

**Issue by sngx13** [carlmontanari/scrapli#258]
**Describe the bug**
Issuing 'write erase' by use of send_interactive isn't working as per documentation.

**To Reproduce**
1. Your script:
```
with Scrapli(** device, comms_return_char='\r\n') as conn:
    erase_config = conn.send_interactive(
        [
            (
                'write erase',
                'Erasing the nvram filesystem will remove all configuration files! Continue? [confirm]',
                '\n'
            )
        ]
    )
print(erase_config, erase_config.result)
```
3. What you're connecting to (vendor, platform, version) Cisco 4331 (IOS-XE 17.3)
4. Output:

```
Response <Success: True> write erase
************************************************************************************************************
Erasing Nvram will not clear license trust code.
************************************************************************************************************
Erasing the nvram filesystem will remove all configuration files! Continue? [confirm]
```

**Expected behavior**
Expected to see the following:

```
[OK]
Erase of nvram: complete
```

**OS (please complete the following information):**
 - OS: Ubuntu 22.04
 - scrapli version: 22.1.30

**Comment by carlmontanari** [comment]
You are not using this correctly. From the docs:

This method accepts a list of "interact_events" -- or basically commands you would like to send, and their expected resulting prompt. A third, optional, element is available for each "interaction", this last element is a bool that indicates weather or not the input that you are sending to the device is "hidden" or obfuscated by the device


Working example:

```
>>> resp = conn.send_interactive([("write erase", "[confirm]"), ("", "vr-csr#")])
>>> resp.result
'write erase\nErasing the nvram filesystem will remove all configuration files! Continue? [confirm]\n[OK]\nErase of nvram: complete\nvr-csr#'
>>>
```

**Comment by sngx13** [comment]
and boom:

```
Response <Success: True> write erase
************************************************************************************************************
Erasing Nvram will not clear license trust code.
************************************************************************************************************
Erasing the nvram filesystem will remove all configuration files! Continue? [confirm]
[OK]
Erase of nvram: complete
CE07-4331#
```

I think documentation maybe a little unclear around this, I've seen it mention sending of '\n' to replicate return key. Maybe worth adding my example in there :-)?

Thank you!
