### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by sngx13** [carlmontanari/scrapli#259]
Hi Carl,

I have a suggestion or a 'feature' request, not sure how complex it would be to get this implemented or maybe you know a way around this already?

I'm looking to use Scrapli to logon to a device which has literally been pulled out of a box brand new with no config on. It would therefore be stuck in the configuration dialog i.e.:

`Would you like to enter the initial configuration dialog? [yes/no]:`

Scrapli times out as it can't find a prompt.

Thank you

**Comment by carlmontanari** [comment]
This can be handled already.

TL;DR: disable auth (auth_bypass: true), then use [read callback](https://github.com/carlmontanari/scrapli/blob/main/scrapli/driver/generic/sync_driver.py#L446-L525) and/or just a while true and read off the channel and handle sending input however you want.

You can look at boxen for examples (its go but its functionally the same)

**Comment by sngx13** [comment]
Thank you, I think I'm being thick but I can't figure out how to use
read_callback() in this instance :| I do have authentication on the console
server so I wouldn't need to disable it. I guess you wouldn't have a dumbed
down example on how i'd string match "dialog" either from the channel or
callback method and send "no" ? :)
