### ISSUE TITLE
My script fails to read my secondary auth when I it goes into a router via ssh

### ISSUE THREAD

**Issue by Ghostwolf73** [carlmontanari/scrapli#277]
I am learning network automation and i am using scrapli with nornir but for some reason my script can't get past the enable password it gives me an error like this 

line 115, in _escalate

raise ScrapliAuthenticationFailed(

scrapli.exceptions.ScrapliAuthenticationFailed: failed escalating privilege from 'exec' to 'privilege_exec'. do you need to set an 'auth_secondary' password?

^^^^ END send_command ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by carlmontanari** [comment]
https://carlmontanari.github.io/scrapli/user_guide/basic_usage/#basic-driver-arguments

“auth_secondary” is what you’re looking for. Please don’t open issues for help/how-tos.
