### ISSUE TITLE
Login prompt "user name:"

### ISSUE THREAD

**Issue by KlimchevKonstantin** [carlmontanari/scrapli#280]
## Question

Good day!

in scrapli to define login prompt (scrapli/channel/base_channel.py) "BaseChannel":

```
self._auth_telnet_login_pattern = r"^(.*username:)|(.*login:)\s?$"
```

But the hardware gives prompt "user name:" (with space)  
If I prescribe in "BaseChannel"

```
self._auth_telnet_login_pattern = r"^(.*username:)|(.*login:)|(.*user name:)\s?$"
```
everything starts working.  

Can you please tell me how best to detect a prompt with a space that is not registered in the BaseChannel?  
I understand that this can be done via @auth_telnet_login_pattern.setter.  
But i dont know how to do it

Thank you

**Comment by carlmontanari** [comment]
yep, the setter is the way to do it:

```
ipdb> conn.channel._auth_telnet_login_pattern
'^(.*username:)|(.*login:)\\s?$'
ipdb> conn.channel.auth_telnet_login_pattern = "my pattern"
ipdb> conn.channel._auth_telnet_login_pattern
'my pattern'
ipdb>
```

going to close this out as I dont think there's anything bug-y here -- in the future please use discussions for questions!

carl
