### ISSUE TITLE
Question: Viability of using synchronization primitives within async on_open and on_close

### ISSUE THREAD

**Issue by rlad78** [carlmontanari/scrapli#284]
First off, I've got to give my thanks to you and the contributors who worked on this project. I have had nothing but great experiences with Scrapli, especially with all the flexibility that's built-in.

I've been using BoundedSemaphores in my async script to limit the number of concurrent asyncssh connections while they perform their necessary operations. This is entirely fine, but I recently encountered an issue where I was forgetting to close connections before releasing the semaphore lock. This got me thinking about on_open and on_close.

In the contributors (or any other experienced users) opinions, are user functions supplied to `on_open` and `on_close` called reliably enough to warrant handling the acquisition and releasing of async locks?

**Comment by carlmontanari** [comment]
👋 hey @rlad78 thanks for the kind words!


> In the contributors (or any other experienced users) opinions, are user functions supplied to on_open and on_close called reliably enough

I should think "yes"! on open is *always* called (if set) during open, and the same is true for on close... for the latter obviously you'd still have to remember to call close (either manually or just letting a context manager do it for you). id imagine in your custom on open/close you could call some other func / access some global to get a lock and acquire/release it for a given connection.

is there any reason you'd think they *wouldnt* be called reliably?

**Comment by rlad78** [comment]
Hi @carlmontanari ! Thanks for the quick response. I didn't want to be naive and assume they were always guaranteed to be called. Never know if something like an exception raised from a connection loss could throw the normal process flow off.

Appreciate the reassurance 👍

**Comment by carlmontanari** [comment]
ah fair -- yeah I think in the timeout scenario it wont (see the well timed #285) -- will investigoogle things a bit this weekend I hope and report back; and/or if you're open to lookin at the other issue and maybe seeing if you see a good path in a pr that would be great too!

**Comment by carlmontanari** [comment]
I think I'll go ahead and close this one and invite ya to chime in over in #285 if that works. defo lemme know if these are different things though (I think they are actually extremely well timed similar things though!)
