### ISSUE TITLE
Custom SSH Password Prompt of "Enter PASSCODE:"

### ISSUE THREAD

**Issue by cmason3** [carlmontanari/scrapli#295]
**Describe the bug**
We use RSA SecurID to authenticate against Cisco and Juniper devices which changes the login prompt to "Enter PASSCODE:". I can see how to change this using `telnet_password_prompt`, but there is no equivalent for SSH.

**To Reproduce**
1. Implement RSA SecurID authentication in IOS-XR :)
2. My script

```
from scrapli.driver import GenericDriver
from getpass import getpass

device = {
  'host': 'xxxx',
  'auth_username': input('Username: '),
  'auth_password': getpass('Enter PASSCODE: '),
  'auth_strict_key': False
}

with GenericDriver(**device) as c:
  c.send_command('terminal length 0')
  print(c.send_command('show version'))
```

**Expected behavior**
There should be the ability to change the expected username and password prompts under SSH.

**Stack Trace**
```
DEBUG:scrapli.channel:read: b'Enter PASSCODE: '
CRITICAL:scrapli.channel:operation timed out, closing connection
DEBUG:scrapli.transport:closing transport connection to 'xxxx' on port '22'
DEBUG:scrapli.channel:read: b'\n'
DEBUG:scrapli.transport:transport connection to 'xxxx' on port '22' closed successfully
Traceback (most recent call last):
  File "/home/user/fetch.py", line 25, in <module>
    main()
  File "/home/user/fetch.py", line 18, in main
    with GenericDriver(**device) as c:
  File "/venv/python3/lib64/python3.9/site-packages/scrapli/driver/base/sync_driver.py", line 42, in __enter__
    self.open()
  File "/venv/python3/lib64/python3.9/site-packages/scrapli/driver/base/sync_driver.py", line 88, in open
    self.channel.channel_authenticate_ssh(
  File "/venv/python3/lib64/python3.9/site-packages/scrapli/decorators.py", line 216, in decorate
    return _multiprocessing_timeout(
  File "/venv/python3/lib64/python3.9/site-packages/scrapli/decorators.py", line 108, in _multiprocessing_timeout
    return _handle_timeout(
  File "/venv/python3/lib64/python3.9/site-packages/scrapli/decorators.py", line 134, in _handle_timeout
    raise ScrapliTimeout(message)
scrapli.exceptions.ScrapliTimeout: timed out during in channel ssh authentication
```

**OS (please complete the following information):**
 - OS: Red Hat Enterprise Linux 8
 - scrapli version - 2023.01.30

**Comment by cmason3** [comment]
That does have the desired affect if I switch from using a context manager.

```
  c = GenericDriver(**device)
  c.channel.auth_password_pattern = r'PASSCODE:'
  c.open()
  c.send_command('terminal length 0')
  print(c.send_command('show version'))
```

How difficult would it be to allow it via GenericDriver so we can continue with a context manager, e.g:

```
  device = {
    'host': 'xxxx',
    'auth_username': input('Username: '),
    'auth_password': getpass('Enter PASSCODE: '),
    'auth_password_pattern': r'PASSCODE:',
    'auth_strict_key': False
  }
```

Is there a documentation link to the `auth_password_pattern` property as I couldn't find it?

**Comment by cmason3** [comment]
Actually, not a massive issue not using a context manager - happy to set it before calling `open()`.

**Comment by carlmontanari** [comment]
nice, glad thats working then! re docs: honestly probably its not really documented... too many things to keep up with!

I think we can/should be exposing this so it can be used w/ context manager. will take a peak this weekend.

**Comment by carlmontanari** [comment]
hey @cmason3 -- can ya take a peak at #296 and let us know if that looks cool/works well for ya?

**Comment by carlmontanari** [comment]
🥳 thanks again! closing as fixed !
