### ISSUE TITLE
Python 3.12: ModuleNotFoundError Upon Import

### ISSUE THREAD

**Issue by MrPaulAR** [carlmontanari/scrapli#307]
**Describe the bug**
Using a new virtual environment on 3.12.0 I get the following error.  If I create a virtual environment no 3.11.x I do not get the error.

``` text
Python 3.12.0 (main, Oct 31 2023, 10:12:33) [GCC 13.2.1 20231011 (Red Hat 13.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scrapli
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/user-gW7Uba4Z/lib/python3.12/site-packages/scrapli/__init__.py", line 2, in <module>
    from scrapli.driver.base import AsyncDriver, Driver
  File "/home/user/.local/share/virtualenvs/user-gW7Uba4Z/lib/python3.12/site-packages/scrapli/driver/__init__.py", line 2, in <module>
    from scrapli.driver.base import AsyncDriver, Driver
  File "/home/user/.local/share/virtualenvs/user-gW7Uba4Z/lib/python3.12/site-packages/scrapli/driver/base/__init__.py", line 2, in <module>
    from scrapli.driver.base.async_driver import AsyncDriver
  File "/home/user/.local/share/virtualenvs/user-gW7Uba4Z/lib/python3.12/site-packages/scrapli/driver/base/async_driver.py", line 6, in <module>
    from scrapli.driver.base.base_driver import BaseDriver
  File "/home/user/.local/share/virtualenvs/user-gW7Uba4Z/lib/python3.12/site-packages/scrapli/driver/base/base_driver.py", line 11, in <module>
    from scrapli.helper import format_user_warning, resolve_file
  File "/home/user/.local/share/virtualenvs/user-gW7Uba4Z/lib/python3.12/site-packages/scrapli/helper.py", line 10, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**To Reproduce**

1. Create virtual enviornment.  I haven't tested with venv or virtualenv but I expect it will be the same result.  `pipenv install --python 3.12 scrapli`
2. Start the python shell with `pipenv run python`
3. Import scrapli with `import scrapli`
4. Observe the error

**OS (please complete the following information):**

- OS:
  - Ubuntu 22.04
  - Rocky 9.2
  - Fedora 38
- scrapli version: 2023.7.30

**Comment by MrPaulAR** [comment]
Looks like `setuptools` is not included with python 3.12 any longer.  Workaround was for me to install that into the virtual environment and the import worked as expected.

**Comment by carlmontanari** [comment]
👋 hey @MrPaulAR thanks for raising this and for finding a fix! can you give the branch over in #308 a crack and see if that sorts it out? if that looks good can merge that and do a post for the last release

**Comment by MrPaulAR** [comment]
Thanks.  This seems to have got past the missing requirement upon import.  This is a new virtual environment so no lingering packages.

```
> pipenv --python 3.12 install git+https://github.com/carlmontanari/scrapli.git@refactor/housekeeping 
> pipenv run python
Python 3.12.0 (main, Oct 31 2023, 10:12:33) [GCC 13.2.1 20231011 (Red Hat 13.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scrapli
>>> quit()
```

**Comment by carlmontanari** [comment]
awesome thanks for confirming! will fix my darglint linting complaints in that pr and merge! will close this, holler if anything else crops up, and thanks again!

**Comment by killjoy1221** [comment]
I don't think that fix is sufficient. Some package managers like pdm don't install setuptools by default.

The best solution is to go full `importlib.resources`. It was added in Python 3.7, so I see no issues in using it. Otherwise, there's a backport that can be used via `importlib_resources; python_version < 3.7`

**Comment by carlmontanari** [comment]
hey @killjoy1221 -- good to know (im clearly not in python space as often anymore :p)! would you be up for a quick pr for that? we're not supporting 3.6 at this point so no need to faff about w/ back port! otherwise I can pick this up this weekend probably

**Comment by carlmontanari** [comment]
sorted by @killjoy1221 in #311 -- thank you much!
