### ISSUE TITLE
Possible change to docs

### ISSUE THREAD

**Issue by exe-r** [carlmontanari/scrapli#310]
**Describe the bug**
Hello, thanks for the great project, I am quite new to this. Wanted to ask regarding this part of the [doc](https://github.com/carlmontanari/scrapli/blob/main/docs/user_guide/installation.md?plain=1#L67)

Is this still relevant? I tried to install it on a new machine but i get the following:

```sh
pip3 install scrapli[full]
Requirement already satisfied: scrapli[full] in ./.local/lib/python3.9/site-packages (2023.7.30)
WARNING: scrapli 2023.7.30 does not provide the extra 'full'
```

My understanding is there are only [these](https://pypi.org/search/?q=scrapli) packages available and the following [transports](https://carlmontanari.github.io/scrapli/user_guide/project_details/#transports) available but "system" is the OS ssh client and "full" should not exist as extra package, the rest can be correctly install as .i.e. `pip install scrapli[paramiko]` etc 

Thanks in advance

**Comment by carlmontanari** [comment]
hmm... I think `full` must have got killed off in the migration to pyproject.toml... my bad :)

[these](https://github.com/carlmontanari/scrapli/blob/main/pyproject.toml#L68-L75) should all work (like pip install scrapli[community] etc.) still.

I suspect we could fairly easily add `full` back in in the pyproject.toml -- worst case maybe that means having a requirements-full.txt and adding a line like the above linked stuff; but would be nicer if there is a way to do it w/out adding that file (I'm just not sure off the top of my head). would you be up for a pr to get this sorted out?

**Comment by exe-r** [comment]
> hmm... I think `full` must have got killed off in the migration to pyproject.toml... my bad :)
> 
> [these](https://github.com/carlmontanari/scrapli/blob/main/pyproject.toml#L68-L75) should all work (like pip install scrapli[community] etc.) still.
> 
> I suspect we could fairly easily add `full` back in in the pyproject.toml -- worst case maybe that means having a requirements-full.txt and adding a line like the above linked stuff; but would be nicer if there is a way to do it w/out adding that file (I'm just not sure off the top of my head). would you be up for a pr to get this sorted out?
> 
> _edit_ and/or a pr to docs would be cool too if you're up for it, either way :)

Thanks for the quick reply, that would be a great opportunity to start contributing ! Let me have a look and have a go with a pr

**Comment by carlmontanari** [comment]
ill go ahead and close this for now, but defo feel free to pop back w/ any doc update prs at any time, they are much appreciated!
