### ISSUE TITLE
Replace darglint with pydoclint

### ISSUE THREAD

**Issue by killjoy1221** [carlmontanari/scrapli#312]
You should consider switching away from darglint. It's very slow, and [`pydoclint`](https://github.com/jsh9/pydoclint) is 1000x faster. I tested it locally and it completed instantly, while darglint took several minutes.

**Comment by carlmontanari** [comment]
*nod* yeah been on my list to replace for a while, will give pydoclint a spin this weekend. I think if I recall darglint is last thing preventing gutting setup.cfg too so that would b great if pydoclint plays nice w/ pyproject.toml! thanks for the suggestion @killjoy1221 !

**Comment by carlmontanari** [comment]
did a very brief check and seems like it will defo not be an easy 1:1 swap cuz of some of the way docstrings are in scrapli sadly. quick example: every single func has raises/returns and just have `N/A` for things, pydoclint and docsig dislike this very much haha. probably they are "right" and I have a bad setup but... will be more effort than I care to deal w/ in the short term so going to back burner this again. realistically not a ton of commits happening and i don't mind wasting gh actions time to run darglint 😁
