### ISSUE TITLE
Examples for Async Drivers would be helpful

### ISSUE THREAD

**Issue by jarora11** [carlmontanari/scrapli#32]
Could you please provide some examples/usage for the async drivers? Do the async drivers function asynchronously across multiple devices or on a single device for multiple functions?
From what I can see, the async drivers would use the exact same inputs as the standard sync drivers (which seem to be a single device in netmiko format). Could we give it a list of dict's and expect it to handle all of them asynchronously?

**Comment by carlmontanari** [comment]
Hi @jarora11 

There is a very simple example [here](https://github.com/carlmontanari/scrapli/blob/master/examples/async_usage/async_iosxe_driver.py)

You are correct that the async drivers have the same API/accept the same inputs/etc.. Scrapli doesn't do any thing more than provide you an asyncio compatible driver, so you'll need to handle the event loop and how/where you spawn connections and such. Here is a simple example that I can add to the examples directory sometime soon:

```python
"""examples.async_usage.async_multiple_connections"""
import asyncio

from scrapli.driver.core import AsyncIOSXEDriver, AsyncNXOSDriver

IOSXE_DEVICE = {
    "host": "172.18.0.11",
    "auth_username": "vrnetlab",
    "auth_password": "VR-netlab9",
    "auth_strict_key": False,
    "transport": "asyncssh",
    "driver": AsyncIOSXEDriver,
}

NXOS_DEVICE = {
    "host": "172.18.0.12",
    "auth_username": "vrnetlab",
    "auth_password": "VR-netlab9",
    "auth_strict_key": False,
    "transport": "asyncssh",
    "driver": AsyncNXOSDriver,
}

DEVICES = [IOSXE_DEVICE, NXOS_DEVICE]


async def gather_version(device):
    """Simple function to open a connection and get some data"""
    driver = device.pop("driver")
    conn = driver(**device)
    await conn.open()
    prompt_result = await conn.get_prompt()
    version_result = await conn.send_command("show version")
    await conn.close()
    return prompt_result, version_result


async def main():
    """Function to gather coroutines, await them and print results"""
    coroutines = [gather_version(device) for device in DEVICES]
    results = await asyncio.gather(*coroutines)
    for result in results:
        print(f"device prompt: {result[0]}")
        print(f"device show version: {result[1].result}")


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())

```

I'm going to close this as I want to reserve issues for bugs and such, but feel free to join networktocode slack where you can find a `scrapli` channel, and of course `python` and other good stuff like that.

Carl
