### ISSUE TITLE
Cisco Banner config with multi-lines causes timeout

### ISSUE THREAD

**Issue by mcmitch** [carlmontanari/scrapli#342]
**Describe the bug**
Scrapli produces a timeout when trying to config a banner motd when the banner contains a new line.

**To Reproduce**
1. Your script
```python
bannerTest = 'banner motd #Test\ntest#'

command_results = nr.run(task=send_configs, configs=[bannerTest], )
```
3. What you're connecting to (vendor, platform, version)
Device is running Cisco IOS XR, not tried reproducing on IOS XR

**Expected behavior**
It should be possible to configure a banner message that contains new lines

**OS (please complete the following information):**
 - OS: Ubuntu
 - scrapli version: 2024.01.30

**Additional context**
Tested with nornir

**Comment by mcmitch** [comment]
Example of pure scrapli scripts that works
```python
from scrapli.driver.core import IOSXRDriver
from os import getenv


my_device = {
    "host": "10.0.0.1",
    "auth_username": getenv("USER"),
    "auth_password": getenv("PASS"),
    "auth_strict_key": False,
}

with IOSXRDriver(**my_device) as conn:
    response = conn.send_configs(["banner motd # test #", "commit"])

print(response.result)
```

and failing example
```python
from scrapli.driver.core import IOSXRDriver
from os import getenv


my_device = {
    "host": "10.0.0.1",
    "auth_username": getenv("USER"),
    "auth_password": getenv("PASS"),
    "auth_strict_key": False,
}

with IOSXRDriver(**my_device) as conn:
    response = conn.send_configs(["banner motd # test\ntest #", "commit"])

print(response.result)
```

**Comment by carlmontanari** [comment]
[example](https://github.com/carlmontanari/scrapli/blob/main/examples/banners_macros_etc/iosxe_banners_macros_etc.py) with explanation in there

**Comment by mcmitch** [comment]
Thanks, it looks like I also hit a different issue, as the `eager=True` doesn't seem to be working with send_configs.

**Comment by carlmontanari** [comment]
I just reran the example verbatim and it works as expected. if you are using a platform that has to commit things, do that in a separate config set that you send -- you want to use eager as little as possible. 

im going to close this. feel free to reopen if you have identified an issue, or feel free to open a discussion to ask for help/talk about it more.
