### ISSUE TITLE
Context manager leaves connection open if exception occurs during __enter__

### ISSUE THREAD

**Issue by Basskip** [carlmontanari/scrapli#345]
**Describe the bug**
The Driver context manager will not perform any cleanup if an exception occurs during the \_\_enter\_\_ call

**To Reproduce**
Try and run a command with invalid credentials
```
my_device = {
    "host": "172.18.0.11",
    "auth_username": "scrapli",
    "auth_password": "not_the_right_password",
    "auth_strict_key": False,
}

with GenericDriver(**my_device) as conn:
    response = conn.send_command("command doesnt matter as it wont be run")
```

This raises a ScrapliAuthenticationFailed as expected, but because the exception occurs during the \_\_enter\_\_ call (\_\_enter\_\_ -> open -> channel_authenticate_ssh), the \_\_exit\_\_ for the context manager isn't ever invoked so close() is never called and the transport/channel are left open

**Expected behavior**
It would be nice if the transport/channel were closed

**Additional context**
For anyone else coming across this issue, I've worked around it by wrapping the driver I'm using, in my case GenericDriver
```
class WrappedGenericDriver(GenericDriver):
    def __enter__(self):
        try:
            return super().__enter__()
        except Exception:
            self.close()
            raise
```

Leaving the unauthed channels open was a problem because they ended up running into the LoginGraceTime for the target device and incurring a penalty

**Comment by carlmontanari** [comment]
nice, thanks for reporting this @Basskip ! Should be fixed [here](https://github.com/carlmontanari/scrapli/commit/5e6fe14df0d04b89e2994d61b156e4428106eb72) ! Holler if that doesn't work for whatever reason!

**Comment by Basskip** [comment]
Looks great, thanks for all your hard work
