### ISSUE TITLE
Support versions of ntc-templates > 4.4.0

### ISSUE THREAD

**Issue by salvapinyol** [carlmontanari/scrapli#346]
Hi:

Is possible to change file [requirements-textfsm.txt](https://github.com/carlmontanari/scrapli/blob/main/requirements-textfsm.txt)
to support new versions of ntc-templates? Current vesion of ntc-templates is 6.0.0.

Thanks,

**Comment by carlmontanari** [comment]
Not sure! If you can test it and all the template lookups still work then yeah of course we can raise the pin. I think at one point template lookup or path or something changed so I put the upper limit on it, but yeah happy to bump it if it’s all good. If you’re down for a pr thatd be great!

**Comment by carlmontanari** [comment]
resolved by #347 thanks again @salvapinyol !
