### ISSUE TITLE
Error in regex for juniper_junos prompt detection on MX and PTX platform.

### ISSUE THREAD

**Issue by kido5217** [carlmontanari/scrapli#359]
**Describe the bug**

Juniper routers (MX104 and higher and PTX series) with more than one RE (routing engine) show current RE status in prompt.

For example, exec mode:

```
{master}
kido@MX-104-PE1>
```

Configuration mode:

```
{master}[edit]
kido@MX-104-PE1#
```

Regex in [scrapli/driver/core/juniper_junos/base_driver.py](https://github.com/carlmontanari/scrapli/blob/main/scrapli/driver/core/juniper_junos/base_driver.py) does not catch `{master}` as part of the prompt.

**To Reproduce**

1. Connect to Juniper MX/PTX
2. Run any `show` command
3. In `result` last line will be `{master}` (or `{backup}` if you've connected to backup RE).

**Expected behavior**

`{master}` or `{backup}` should not be included in the result.

**OS**

- RHEL8/9
- Python 3.9
- SCrapli 2024.7.30

**Additional context**

I propose changing this part or pattern in `exec`, `configuration`, `configuration_exclusive` and `configuration_private`:

```
{\w+:\d}
```

To this:

```
{\w+(:\d){0,1}}
```

I can make a PR for this.

**Comment by carlmontanari** [comment]
👋 hey @kido5217 sure, pr is most welcome -- please make sure to add a test too!
