### ISSUE TITLE
Adding serial devices as a transport

### ISSUE THREAD

**Issue by 991jo** [carlmontanari/scrapli#37]
I currently have a little project that needs to interact with some switches via a serial port and I am thinking about implementing that for scrapli.

After a short look into the code it does not look that hard to implement. Basically its just an other transport class with a couple of different arguments and some changes in the ScrapeBase class or am I missing something?

**Comment by carlmontanari** [comment]
Hi @991jo 

Nope, sounds like you've got the gist of it! You'd need to build a new transport class -- subclass `Transport` and make it look probably an awful lot like the telnet transport. The transports should all be 99% decoupled from the drivers/channel -- so there shouldn't be any changes in ScrapeBase other than perhaps adding a `transport_serial_port` argument or something like that. I suspect auth/login handling would be the only sort of pain point -- I recently overhauled some of the telnet auth handling that would probably provide a pretty solid starting point for the serial stuff (you may even be able to just subclass the Telnet transport and not super to it or just override telnet init things after calling super -- not totally sure, just thinking out loud here!). 

I assume you'd use pyserial or something else not standard library? If so, one thing that I want to be sure about is that any third party packages are not required to run scrapli -- so the imports for this would need to live in the transport class itself so they are only loaded up if a user wants to use that transport (you can go back in time and look at when paramiko was in scrapli "core" to see some hack job I did to make that work -- improvements welcome :)).

Happy to chat here or ntc slack or wherever if ya wanna talk it through just lmk!

Carl

**Comment by carlmontanari** [comment]
One last thought for now -- I *think* I'd want to make this its own library like how scrapli_paramiko/scrapli_asyncssh. The reasons for this are:

1. I *assume* (maybe a bad assumption!) that this would include third party packages like pyserial -- all the other transports got pulled out of scrapli core to make handling this easier/have a cleaner separation between "core" (bare minimum required to do stuff -- driver/transport/channel bases/logic) and optional additional stuff like different transports
2. Testing this seems like it may be really tough -- of course unit testing stuff will be simple, but I dont know of a good way to repeatably (in a container in GitHub Actions) test connecting to a serial port off the top of my head. I really want to ensure that scrapli core stays super thoroughly tested and that there is a clear and obvious delineation between core/non-core things.

Its very possible I am making and assumptions about things though and these points are perhaps not really true/valid, so for sure let me know if I'm saying silly stuff!

Carl

**Comment by 991jo** [comment]
thanks for the response, good that you can confirm my first thoughts regarding what needs to be done.

If including more 3rd party packages is an issue I will take a look at how much more painful it is to do this with plain python.
My initial plan was to use a library for this.
I also think that connecting to a serial port in a container could get a bit messy, but maybe this can be emulated somehow.

regarding making it a plugin: It took me a lot of time to find the repos for scrapli_paramiko because it is neither in your profile nor linked in the README, although the README mentions paramiko half a dozen times. But I found it in the end and will take a look at it.

Greetings
Jo
Jo

**Comment by carlmontanari** [comment]
Ohhhh good call. Thats a big miss -- I will add links to all the other scrapli "family" repos... thanks for pointing that out!! (on my todo list for this weekend now!)

Using third party stuff is totally ok, I just dont want it to be required to run "core" scrapli -- i.e. a user should be able to connect using the system (default) transport w/out ever having to have any third party packages installed. If that user decided to use the serial transport, then the required packages can be imported in that transport class though. Hopefully that makes sense!

Carl

**Comment by carlmontanari** [comment]
FYI -- I added a "related scrapli libraries" section to the readme with links to the other repos! Currently this is just in develop [here](https://github.com/carlmontanari/scrapli/tree/develop#related-scrapli-libraries). Thanks for pointing that out, that was silly to not have links here!

Carl

**Comment by 991jo** [comment]
A short update:
I have added a new serial transport. I currently have no tests for it.
I do not plan to work on this any further because what I want to do can be achieved with tools like ser2net which map serial interfaces to telnet connections. This allows me to use the telnet transport.

**Comment by carlmontanari** [comment]
Ah thats a great idea! (ser2net+"normal" telnet, way easier!)

Thanks for the update @991jo !!
