### ISSUE TITLE
Setting Timeouts per command

### ISSUE THREAD

**Issue by 991jo** [carlmontanari/scrapli#40]
Hello

I have a couple of commands that take a long time to complete (e.g. copy a new firmware from a tftp/ftp/http/whatever server to the router). Without changing the `timeout_ops setting` those run into the timeout.
If I set the `timeout_ops` while initializing the Driver this timeout is valid for all operations. But I dont want to wait several minutes for regular commands to fail.

Is there a better solution for this?

**Comment by carlmontanari** [comment]
Hey @991jo 

Currently the way to do that would be something like this:

```
device = {
	"host": "172.31.254.1",
	"auth_strict_key": False,
	"auth_username": "vrnetlab",
	"auth_password": "VR-netlab9",
	"timeout_ops": 1
}

conn = IOSXEDriver(**device)
conn.open()

print("timeout value as set in the constructor --> ", conn.channel.timeout_ops)

# update it to 5s before running some long running command
conn.channel.timeout_ops = 5
print("timeout value is now 5s --> ", conn.channel.timeout_ops)

# run the long running command... zzzzzzz.... :) 

# set it back to 1s after long running command
conn.channel.timeout_ops = 1
print("timeout value is back to 1s--> ", conn.channel.timeout_ops)
```

Which would print out something like this:

```
timeout value as set in the constructor -->  1
timeout value is now 5s -->  5
timeout value is back to 1s-->  1
```

So not super elegant right now to be honest, but should do the trick. I may add an argument to the send command(s)/config(s) methods to set the timeout per operation but haven't gotten around to that yet!

Think that'll work for you for now?

Carl

**Comment by 991jo** [comment]
Thanks for the quick response.

As you said, it is not very elegant, but it works for now.
The timeout parameter per method would be a lot cleaner.

**Comment by carlmontanari** [comment]
Cool! Its on the to do list so it will get done eventually, I promise :D!

**Comment by carlmontanari** [comment]
@991jo -- got around to a first draft of a nicer way to deal with timeouts.

https://github.com/carlmontanari/scrapli/blob/develop/scrapli/driver/network_driver.py#L246

^ there is a keyword only argument that you can pass on all the `send_command(s)(_from_file)` and `send_Config(s)(_from_file)` methods. And a decorator to set the timeout for the duration of that method call and set it back when done: https://github.com/carlmontanari/scrapli/blob/develop/scrapli/decorators.py#L341

This is just in dev for now, but wanted to let you know. Let me know if you test it out and have any thoughts about it!

Carl
