### ISSUE TITLE
AsyncGenericDriver doesn't work

### ISSUE THREAD

**Issue by LF3551** [carlmontanari/scrapli#83]
I can't understand how to use AsyncGenericDriver, it's crashed every time with this error
_[TransportPluginError("Attempting to use transport type system with an asyncio driver, must use one of ['asyncssh'] transports")]_
could you advise me some of your examples
```
from pprint import pprint
import yaml
from scrapli.driver import AsyncGenericDriver
import scrapli
import asyncio

async def send_command_to_devices(ip_address):
    my_device = {
        "host": ip_address,
        "auth_username": login,
        "auth_password": password,
        "auth_strict_key": False,
    }
    async with AsyncGenericDriver(**my_device) as conn:
        find_hostname = await conn.send_command("get system status | grep Hostname")
        data1= find_hostname.result
        print(data1)

async def send_command_fortinet(devices):
    coroutines = [send_command_to_devices(device) for device in devices]
    result_all = await asyncio.gather(*coroutines, return_exceptions=True)
    print(result_all)
    for device, result in zip(devices, result_all):
        if isinstance(result, Exception):
            print(f"error {device}", result)
    return result_all
if __name__ == "__main__":
    devices = ['192.168.5.1']
    result = asyncio.run(send_command_fortinet(devices))
    print(result)
```

**Comment by carlmontanari** [comment]
Hey @LF3551 

You need to pass a `transport` to use that is asyncio, here's a basic [example](https://github.com/carlmontanari/scrapli/blob/master/examples/async_usage/async_iosxe_driver.py#L11)

And some doc info about transports [here](https://carlmontanari.github.io/scrapli/user_guide/advanced_usage/#using-a-different-transport)

You may want to check out the `community` repo too -- there is at least a wireless foritnet platform [there](https://github.com/scrapli/scrapli_community/tree/master/scrapli_community/fortinet) I'm not sure how much overlap there is with other fortinet things, but it may be easy for you to make a platform from that or even just use that directly.

Going to close as I dont think this is a bug/issue, but feel free to use the [`discussions`](https://github.com/carlmontanari/scrapli/discussions) thing here on GitHub or join networktocode slack and pop in the scrapli channel there for more chatting!

Carl
