### ISSUE TITLE
Can't get sample test with Generic driver to work against Linux system

### ISSUE THREAD

**Issue by allan-silverstein** [carlmontanari/scrapli#86]
Hi,
I've been using Netmiko for a while but wanted to give scrapli a try to hopefully take advantage of speed.  My goal is to get this working against Drivenets boxes but my initial attempt using the generic_driver.py example did not go well, as I couldn't even log in (got stuck here: conn = GenericDriver(**MY_DEVICE).    With that said, I tried the same simple script against an Ubuntu box with the hope of just logging in and issue a "pwd".  It gets hung and times out at conn.send_command.  Here is the the example against the Ubuntu system:

```
from scrapli.driver import GenericDriver

MY_DEVICE = {
    "host": "172.17.206.92",
    "auth_username": "xxxx",
    "auth_password": "xxxxxx",
    "auth_strict_key": False,
}

def main():
    """Simple example of connecting to an IOSXEDevice with the GenericDriver"""
    # the `GenericDriver` is a good place to start if your platform is not supported by a "core"
    #  platform drivers
    conn = GenericDriver(**MY_DEVICE)
    print(f"conn.transport.open_cmd: {conn.transport.open_cmd}")
    conn.open()
    print("hello2")

#   print(conn.channel.get_prompt())
    print(conn.send_command("pwd").result)
    print("hello3")
    conn.close()

if __name__ == "__main__":
    main()
```

Here is what happens when I run it:

```
$ python sample.py
conn.transport.open_cmd: ['ssh', '172.17.206.92', '-p', '22', '-o', 'ConnectTimeout=15', '-o', 'ServerAliveInterval=30', '-l', 'as2863', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-F', '/dev/null']
hello2
Traceback (most recent call last):
  File "sample.py", line 34, in <module>
    main()
  File "sample.py", line 28, in main
    print(conn.send_command("pwd").result)
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/driver/generic/sync_driver.py", line 168, in send_command
    timeout_ops=timeout_ops,
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/decorators.py", line 408, in decorate
    result = wrapped_func(*args, **kwargs)
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/driver/generic/sync_driver.py", line 132, in _send_command
    channel_input=command, strip_prompt=strip_prompt, eager=eager
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/decorators.py", line 278, in decorate
    kwargs=kwargs,
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/decorators.py", line 335, in _multiprocessing_timeout
    self._handle_timeout()
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/decorators.py", line 311, in _handle_timeout
    raise ScrapliTimeout(self.message)
scrapli.exceptions.ScrapliTimeout: timed out sending input to device
(p1_netmiko_exper4) as2863@ubuntuP1-SYSlog-S1:~/pythonProjects/p1-automation/scrapli
$
```

Once I get this simple test working, I'll go back to the Drivenets system.  With Drivenets, the conn.open() failed.  Is this the best place to ask these issues.  I can't get on slack, as it is blocked by company I am consulting at.

**Comment by carlmontanari** [comment]
hey @allan-silverstein :wave:

for question stuff slack is probably preference, but also the `discussions` thing here on GitHub is probably a good place. for now this works though. 

99% sure you just need to add `"comms_ansi": True` to your `MY_DEVICE` dict there. I am *probably* going to make this the default/standard here shortly as a lot of devices end up plopping ansi chars in the output and its probably "cheap" enough to not worry about having it be toggle-able. With just adding that your script works nicely against an ubuntu host I have handy.

Let us know if that works!
Carl

**Comment by carlmontanari** [comment]
re being stuck here: `conn = GenericDriver(**MY_DEVICE)` -- would def need to know what error, that doesn't do anything other than create the connection object (meaning there are no "side effects" -- it doesn't open a connection or anything) so that *shouldnt* cause any chaos :)

**Comment by allan-silverstein** [comment]
Excellent. That now works so I now know the package should be installed correctly and working.  Back to the Drivenets box.
Here is a very similar simple test:

```
from scrapli.driver import GenericDriver

#   "host": "au22",
MY_DEVICE = {
    "host": "10.173.125.180",
    "auth_username": "p1automon",
    "auth_password": "xxxxx",
    "auth_strict_key": False,
    "comms_ansi": True,
}

def main():
    """Simple example of connecting to an IOSXEDevice with the GenericDriver"""
    # the `GenericDriver` is a good place to start if your platform is not supported by a "core"
    #  platform drivers
    conn = GenericDriver(**MY_DEVICE)
    print(f"conn.transport.open_cmd: {conn.transport.open_cmd}")
    print("hello1")
    conn.open()
    print("hello2")

#   print(conn.channel.get_prompt())
    print(conn.send_command("show interface | no-more").result)
    print("hello3")
    conn.close()

if __name__ == "__main__":
    main()
```

It fails/timesout at conn.open()

```
$ python sample.py
conn.transport.open_cmd: ['ssh', '10.173.125.180', '-p', '22', '-o', 'ConnectTimeout=15', '-o', 'ServerAliveInterval=30', '-l', 'p1automon', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-F', '/dev/null']
hello1
Traceback (most recent call last):
  File "sample.py", line 29, in <module>
    main()
  File "sample.py", line 20, in main
    conn.open()
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/driver/base/sync_driver.py", line 87, in open
    auth_private_key_passphrase=self.auth_private_key_passphrase,
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/decorators.py", line 278, in decorate
    kwargs=kwargs,
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/decorators.py", line 335, in _multiprocessing_timeout
    self._handle_timeout()
  File "/home/as2863/python-venv/p1_netmiko_exper4/lib/python3.7/site-packages/scrapli/decorators.py", line 311, in _handle_timeout
    raise ScrapliTimeout(self.message)
scrapli.exceptions.ScrapliTimeout: timed out during in channel ssh authentication
```

**Comment by carlmontanari** [comment]
If you want to try changing the transport to paramiko/ssh2 that could quickly see if that gets past any auth stuff, otherwise will need logs.

You can add the following to get channel logging and the "normal" python logs:

```
from scrapli.logging import enable_basic_logging

enable_basic_logging(file=True, level="debug")
```

And add `"channel_log": True` to your `MY_DEVICE`.

If you wanted to try paramiko/ssh2 transport you could add `"transport": "ssh2"` to your `MY_DEVICE`. You'll need to install that like: `pip install scrapli[full]`

**Comment by allan-silverstein** [comment]
Ok, looking at the logs, it looks like it does accept the username/passwd but the format of the output may not be what scrapli is expecting.  Can I send you the log files through a different means, as my client may not want these posted....

**Comment by allan-silverstein** [comment]
Here is the tail portion of the scrapli.log file which should help:.  Notice the device prompt all the way to the right margin.

```
p1automon@10.173.125.180's password: "
10    | 2021-03-02 18:43:35,161 | DEBUG    | 10.173.125.180:22         | write: REDACTED
11    | 2021-03-02 18:43:35,162 | DEBUG    | 10.173.125.180:22         | write: '\n'
12    | 2021-03-02 18:43:35,162 | DEBUG    | 10.173.125.180:22         | read : b'\nDRIVENETS CLI Loading...                                                                                AUTTX22CWP# '
13    | 2021-03-02 18:44:04,968 | CRITICAL | 10.173.125.180:22         | channel operation timed out, closing transport
14    | 2021-03-02 18:44:04,969 | DEBUG    | 10.173.125.180:22         | closing transport connection to '10.173.125.180' on port '22'
15    | 2021-03-02 18:44:05,070 | CRITICAL | 10.173.125.180:22         | encountered EOF reading from transport; typically means the device closed the connection
16    | 2021-03-02 18:44:05,169 | DEBUG    | 10.173.125.180:22         | transport connection to '10.173.125.180' on port '22' closed successfully
```

**Comment by carlmontanari** [comment]
You will probably need to either modify your `comms_prompt_pattern`, see [here](https://carlmontanari.github.io/scrapli/user_guide/advanced_usage/#platform-regex) -- which may not be super desirable as I'm guessing that subsequent prompts are more "normal" (prompt starting at a newline each time).... 

Or set `auth_bypass` -> `True` and provide a custom `on_open` ([docs](https://carlmontanari.github.io/scrapli/user_guide/advanced_usage/#on-open)) to handle the auth/initial login (if you use `ssh2` or `paramiko` transport the auth part won't happen "in channel" as it will happen in either of those libraries, so then you should just have to deal w/ sending a return and getting past any login banner stuff). 

This is because the default pattern is not going to match that as there is no newline before the actual device prompt there.

In any case, I don't see a bug here so I'm going to close this. You can follow this up on slack or in discussions but I'm trying to keep issues for bugs only.

Carl

**Comment by allan-silverstein** [comment]
ok, thx
